name: Automatic tests

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Using Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-

      - name: Maybe install the dependencies
        run: npm install
        if: |
          steps.cache-node-modules.outputs.cache-hit != 'true'

      - name: Run unit tests
        run: npm run test
